# @package _global_
defaults:
- _self_
- method: sum

model: ViT-B-16
num_tasks: 8
specify_lambda: None

DATASETS: ''
DATASETS_VAL: ''

# utilities
cache_dir: None
world_size: 1
port: 12355
device: "cuda"
batch_size: 32
data_location: "datasets"
model_location: "models/checkpoints"
masks_location: "models/tall_masks"
save_subfolder: ""

n_eval_points: 31
early_stopping: true
early_stopping_patience: 3

wandb:
  project: model-merging
  mode: offline
  group: ${model}

hydra:
  run:
    dir: ./logs/${model}/${method.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
